# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"

	(1..2).each do |i|
    if defined?(VagrantVbguest::Middleware)
      config.vbguest.auto_update = true
    end

		config.vm.define "ubuntu#{i}" do |node|
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network :private_network, ip: "192.168.33.2#{i}"
      # node.ssh.shell is required to avoind "stdin: is not a tty" error, ref: http://stackoverflow.com/questions/24421541/vagrant-up-fails-with-stdin-start-ssh-stderr-stdout-errors
      node.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
      node.vm.provision "shell", path: "provisioning.sh"
			node.vm.provider "virtualbox" do |v|
				v.name = "ubuntu#{i}"
        v.customize ["modifyvm", :id, "--cpus", "1", "--memory", "512"]
			end
		end
	end
end
